### ISSUE TITLE
GitLab Type: Use the repository name of the url for directory name

### ISSUE THREAD

**Issue by phortx** [bit3/mgpm#6]
If you have a GitLab Repository Names `foo/Bar` the repository url is `foo/bar`. mgpm will clone it to the directory `Bar`. Better would be the lower case version like in the url: `bar`.

**Comment by tristanlins** [comment]
This was silently fixed in 46dae389b1cc30ca62973f0c941f167d6180f343

**Comment by phortx** [comment]
Awesome! Will there be a new release soon?

**Comment by tristanlins** [comment]
Yes, I'm working on some other tickets atm. When I'm finished, I will make a new release ;-)
