### ISSUE TITLE
Stash and restore lokal changes like git up

### ISSUE THREAD

**Issue by phortx** [bit3/mgpm#7]
Biggest show stopper currently is the fact, that mgpm struggels with local uncommitted changes. Would be glad to see stashing/popping just like [git up](https://github.com/aanand/git-up) uses to do.

**Comment by tristanlins** [comment]
This is done in the new [9th pre-release](https://github.com/bit3/mgpm/releases/tag/1.0.0-SNAPSHOT.9).
