### ISSUE TITLE
Add a status summary with -s flag

### ISSUE THREAD

**Issue by phortx** [bit3/mgpm#9]
If you manage a lot of projects with mgpm (talking about 50 projects actually) with several branches respectively, the output mgpm generates on a `mgpm -uis` call is comparatively long.

Hence a important information is going lost and you have to scroll back thru the outputs in order to get it back: The actual status of a repository. Most important: whether there are uncommited or unpushed changes.

To get rid of this issue, a short list of all repositories which contain uncommited or unpushed changes at the end would be nice.

Another solution would be not to output everything but rather just the repositories with a non trivial state (updated, uncommitted changes etc). That will reduce the output to the minimum of required information.

In order to bring back the original behavior a `-v` (verbose) flag could make sense.

**Comment by tristanlins** [comment]
Implemented in 04d9568d7f3173c5f1b97f916495185b6539c0ba
Release with https://github.com/bit3/mgpm/releases/tag/1.0.0-SNAPSHOT.13
